server:
  port: 9050
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Risk_Calculation25?createDatabaseIfNotExist=true
    username: root
    password: root
    platform: mysql
    continue-on-error: true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      hibernate:
        globally_quoted_identifiers: true
  application:
    name: Risk_Calculation_App
logging:
  file:
    path: /
    name: logs/application.log

